package:
  name: Ligandr
  version: "0.0.0"

source:
  path: ../..

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openeye
    - mdtraj
    - numpy

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - Ligandr

about:
  home: add_url_here
  license: LGPLv3 License
